### ISSUE TITLE
Help avoid dev.down misunderstandings

### ISSUE THREAD

**Issue by robrap** [openedx-unsupported/devstack#1008]
Often people will use `dev.down`, thinking it is the opposite of `dev.up`, and not understanding what it does and that `dev.stop` is more likely what they want.

Proposal:
* Rename `dev.down` to `dev.reset`, and explain what it does in documentation. This would make it much less likely that it would be mistakenly used by a newbie. It may take a little more effort to find by more of a docker expert, but it is more rare that this would be needed as well.
* Possibly introduce `dev.start` as an alias for `dev.up`. This would make the start/stop pair more obvious in language, and would be simpler for newcomers that aren't yet familiar with docker. It would however make the make file even more of an abstraction from docker. This proposal would leave `dev.up` for those that already are used to this, because it doesn't cause an issue on its own, except when `dev.down` also exists.

ACs
- [x] Rename `dev.down` to `dev.remove-containers`
- [x] Add output to `dev.down` to say "dev.down has been renamed to dev.remove-containers. If this doesn't seem like what
you were looking for, you probably want to be using dev.stop instead. See docs for
more details."
- [x] Update docs accordingly.
- [x] Announce this change.

**Comment by robrap** [comment]
FYI: @rgraber @jmbowman @johnnagro

**Comment by johnnagro** [comment]
I am in favor of this change.

**Comment by robrap** [comment]
Doing the simple rename (the first point) is probably faster, and stands on its own as a step forward. The alias could be a separate ticket or effort or deferred indefinitely if it adds a lot of complexity.

**Comment by arbrandes** [comment]
`dev.reset` [already exists](https://github.com/openedx/devstack/blob/master/Makefile#L490).  However `dev.destroy`, which I was going to suggest as more accurate (to my mind "reset" implies you'll get a blank deployment, as opposed to simply tearing everything down), also [already exists](https://github.com/openedx/devstack/blob/master/Makefile#L495)... and it does [exactly](https://github.com/openedx/devstack/blob/master/destroy.sh#L7) what we would want here, but with an additional confirmation step.

So... just remove `dev.down`, then?

**Comment by robrap** [comment]
As someone who knows what `dev.down` does, I have used it on occasion. I don't think of it as `dev.destroy`. If the other names are taken, maybe we use a longer name like `dev.restore-containers-to-current-images`, or some such crazy name? Note: worst case, I think we should just remove `dev.down`, but it is nice to have that functionality when you want it.

**Comment by arbrandes** [comment]
@robrap, but `dev.down` has the exact same end result as `dev.destroy`, just without the confirmation step.  AFAIK, you end up without any containers, volumes or networks; not restored containers.

**Comment by kdmccormick** [comment]
`dev.down` removes containers. It does not remove volumes. The benefit of it is that you will start up next time from whichever images you have pulled most recently, rather than starting your old containers back up. It also gets rid of any ephemeral state that may be accumulating in your containers, such as pip requirements changes or modifications to container system files.

`dev.destroy` removes your containers *and* volumes. In docker-compose speak, that's `docker-compose down -v|--volumes ...`. After destroying, you need to reprovision.

**Comment by robrap** [comment]
@kdmccormick: We can certainly clarify what everything does, but I think the main suggestion on this topic, if we agree we want to leave this, is to find an alternate name for `dev.down`. Do you have a proposed name?

**Comment by kdmccormick** [comment]
Nope, it doesn't matter to me.

**Comment by robrap** [comment]
How about `dev.down` => `dev.remove-containers`?

**Comment by robrap** [comment]
[idea] Maybe `dev.down` could be updated to output a message like:
```
dev.down has been renamed to dev.remove-containers. If this doesn't seem like what
you were looking for, you probably want to be using dev.stop instead. See docs for
more details.
```
