### ISSUE TITLE
Dependencies get out of sync with images

### ISSUE THREAD

**Issue by timmc-edx** [openedx-unsupported/devstack#1013]
One of the most frequent causes of frustration with devstack is that LMS fails to start because the code is out of sync with the virtualenv. This can happen because either:

- The user has run `git pull` on edx-platform, or
- The user has run `make dev.pull.lms` in devstack

Either of these can leave the LMS image with newer code than dependencies, or newer dependencies than code. Even doing both is not necessarily enough, as the latest built image may be a bit behind the latest edx-platform commit.

The usual solution, and the workflow that experienced devstack users know to do, is to always run `make lms-shell` and then inside that run `make requirements`. However, this isn't well documented, and is unnecessarily manual. Compounding this is https://github.com/openedx/devstack/issues/1008 -- devs often use `make dev.down` instead of `make dev.stop`, which means `make requirements` needs to be run all over again.

(This applies to all of the IDAs. LMS is just used here as the most frequent example.)

ACs:
- [x] Add documentation around how to update the code on the container (including information on migrations and requirements). This may need the documentation to be cleaned up to make it clear where these documentation updates should go: https://github.com/openedx/devstack/issues/1014
- [x] Create a ticket for automating requirements updates using the fingerprinting suggestions below. - this is now https://github.com/openedx/devstack/issues/1028

**Comment by robrap** [comment]
I suggest we enhance our docs (common workflows and troubleshooting, etc.) to include the above. We can then use the docs for education. 

I think automating fixes may also help, but that is a bigger lift and won't address all cases. For example, how would automation detect that there is newer code the might resolve your problem if you aren't on the latest code?

**Comment by timmc-edx** [comment]
The automation might be very simple. Currently, the LMS is run by `manage.py runserver` in a loop; Django just shuts down the server when it detects changed source files, and then the loop restarts: https://github.com/openedx/devstack/blob/055a7de1d29335c3e787371c6c5a0988c6b936c1/docker-compose.yml#L432 So, we could put `make requirements` into the loop, and ensure that development.txt is one of the watched files.

Perhaps it might be slow, but in that case we could fingerprint the virtualenv and only run it when the stored fingerprint no longer matches. (`make requirements` takes 20 seconds to run, but `find ~/edx-repos/edx-platform/venv-3.8/ -printf '%P %t %s %i %m %U %G\n' | sort | sha256sum` takes 0.5 seconds.)

**Comment by robrap** [comment]
Note: I think we did something like that, possibly with node?, and there were times where the cached value would get out of sync, which lead to even more difficult to resolve issues. I definitely wouldn't want make requirements fully running all the time. That is what we used to have for the paver commands, and it was a killer.

**Comment by robrap** [comment]
Grooming note: We may want to split this 2 tickets:
- improving documentation around this issue, and 
- potentially automating a fix

**Comment by dianakhuang** [comment]
Running `make requirements` takes about 20 seconds to run, so it seems like the fix will take longer than just reloading the django server.
