### ISSUE TITLE
Devstack documentation deficiencies 

### ISSUE THREAD

**Issue by robrap** [openedx-unsupported/devstack#1014]
Private link https://2u-internal.atlassian.net/wiki/spaces/TNL/pages/170360918/Guided+lab+Develop+with+Devstack is a document to help TNL make use of devstack. Why is an entirely separate set of documentation needed, and how could the devstack docs be improved such that they don't need to be duplicated/fixed elsewhere?

Review in the devstack repo:
- README
- FAQ
- Troubleshooting
- (Common) Workflows

In Confluence:
- Onboarding Guide to devstack (does this still exist?)

ACs
- [ ] Review the Confluence page https://2u-internal.atlassian.net/wiki/spaces/TNL/pages/170360918/Guided+lab+Develop+with+Devstack
- [ ] Update the official devstack documentation with gaps from the page that need to be clarified in the official documentation.
- [ ] Reorganize the official documentation, possibly move some more detailed info into other documents and keep the README barebones, figure out the best ordering for documentation sections, etc.

**Comment by robrap** [comment]
I'm wondering if we already have, or need, a link to this private documentation: https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/53674147/Hosted+devstack+cloud+devstack+devstack+on-demand

**Comment by dianakhuang** [comment]
My current findings on discovery wandering through these pages:
- [Private Confluence Page 1 (Guided Lab)](https://2u-internal.atlassian.net/wiki/spaces/TNL/pages/170360918/Guided+lab+Develop+with+Devstack) - helps orient the user to the wider understanding of developing Open edX as a whole as well. it contains some discussion of setting up hosted devstack, which is not as useful.
- [Private Confluence Page 2 (Hosted devstack)](https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/53674147/Hosted+devstack+cloud+devstack+devstack+on-demand) - I would prefer not to mix up documentation of hosted devstack vs. local devstack.

Current plan of attack:
- try to remove all information that is out of date first
- then see if we can merge together some of the pages like faq/workflows

**Comment by dianakhuang** [comment]
I did do some quick wins on removing/changing some devstack documentation, so I'm going to be closing this for now instead of doing a huge rewrite/change.
