### ISSUE TITLE
Move README documentation in devstack

### ISSUE THREAD

**Issue by robrap** [openedx-unsupported/devstack#1030]
Having much of the documentation live in the README means links to other docs get lost and those docs are never read.

Proposal:
- Move much of the contents of the README to other docs as makes sense.
- Point README to Readthedocs, and have the index page provide a reasonable outline of the docs (what to learn where).

Acceptance Criteria
- [x] Move all the documentation out of the README into a new document.
- [x] Ensure that the README links to the ReadTheDocs site.
- [x] Ensure that links to the README are re-routed to the new location of the text

**Comment by robrap** [comment]
Related, but different, can we review https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449618433/Devstack+Hacks and update the real docs as appropriate and archive this page?

**Comment by ashultz0** [comment]
readme updates are very fast and immediately obvious how to deploy them (merge your change)

readthedocs updates feel much more intimidating

so the prerequisite for this is to make sure that readthedocs updates are as obvious and quick as readme updates so people actually do them

**Comment by ilee2u** [comment]
I think the biggest thing for me as someone who’s been used to monorepos was realizing that devstack actually installs a bunch of repos with a bunch of containers outside of the devstack folder. I feel like some clarity on that infrastructure in the README or otherwise would be helpful.

**Comment by robrap** [comment]
@ashultz0:
> readthedocs updates feel much more intimidating
> 
> so the prerequisite for this is to make sure that readthedocs updates are as obvious and quick as readme updates so people actually do them

Readthedocs should automatically update in the same way. I wonder whether everyone is as intimidated, and regardless, how could we correct this misunderstanding? Maybe instead of "Documentation is on [Read the Docs](https://edx.readthedocs.io/projects/open-edx-devstack/en/latest/)", we could say something like "Documentation is automatically deployed to [Read the Docs](https://edx.readthedocs.io/projects/open-edx-devstack/en/latest/)"?

Note that neither of these sentences will likely be read unless the README is short and sweet. If the documentation sidebar is not a good enough TOC, we could better organize in the doc's index page.

**Comment by jmbowman** [comment]
We can also add auto-builds of previews for PRs on Readthedocs as a GitHub commit check, we already do that in open-edx-proposals and should probably do it in more places: https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by ashultz0** [comment]
I think having it clearly called out and linked on the readme would help.

But automated preview on PR is a game changer. My experience in various repos is the local environment is different enough and the doc build is fiddly enough that certainty isn't available. That may not be true here, but it's too late, I've had the experience in edx repos. If I can easily look, I can PR with confidence.

**Comment by timmc-edx** [comment]
I've done the big move, and while there are still improvements to make, I think this ticket is done. Other improvements should be ticketed out separately.
