### ISSUE TITLE
Don't recommend virtualenv for devstack

### ISSUE THREAD

**Issue by jmbowman** [openedx-unsupported/devstack#1076]
While reproducing the steps that tripped up a new devstack user, I noticed that the Getting Started guide says to set up a Python virtualenv, but most users won't need a virtualenv installed for normal devstack usage.  Only the following tasks would still need a local Python virtualenv:

* Building documentation locally (but this can be deferred to CI and RTD)
* Updating dependencies (but we have a GHA workflow for this)
* Running tests locally (but these are for code most developers never touch)

Especially now that docker-compose has been rolled into Docker, we just shouldn't need to install any Python packages outside of Docker for normal devstack usage.

A/C:
* [x] Verify that most devstack functionality works without a virtualenv
* [x] Update the Getting Started guide to no longer ask new users to set up a virtualenv
* [x] Update any other docs for the handful of tasks still requiring a virtualenv to mention the need and steps for setting one up
* [x] Ensure that the instructions accurately inform Linux users how to get a working docker-compose without using a virtualenv

**Comment by timmc-edx** [comment]
It looks like on current Ubuntu LTS there's a `docker-compose` package that's up to date, whereas the `docker.io` package (version 20.10.21) does not yet support the `docker compose` subcommand. So I think we'll need to stick with `docker-compose` for now.
