### ISSUE TITLE
Devstack Issues on Apple Silicon

### ISSUE THREAD

**Issue by dianakhuang** [openedx-unsupported/devstack#1077]
A/C:
- [ ] Document issues with Apple Silicon so we can take action on them.

Implementation Details:
- [ ] Follow up with folks mentioned in [this Slack thread](https://twou.slack.com/archives/C030CC8T40N/p1684511495785219) who have had issues with devstack on Apple Silicon machines, and collect details of what didn't work
- [ ] Reach out to everyone we can find who has recently set up devstack and collect any issues they report
- [ ] Ticket the reported issues so we can start fixing them
- [ ] Update the devstack troubleshooting documentation page if necessary, make sure all new devstack users are made aware that it exists before they start installing devstack

Issues discovered:

```[tasklist]
### Apple Silicon Issues
- [ ] https://github.com/openedx/devstack/issues/1083
```

**Comment by jmbowman** [comment]
Private Slack thread with names of people who seem to have been impacted: https://twou.slack.com/archives/C030CC8T40N/p1684511495785219

**Comment by dianakhuang** [comment]
The FED-BOM team has gotten hold of an Apple Silicon Mac and it seems like the biggest issue is related to: https://github.com/openedx/devstack/issues/1072

**Comment by dianakhuang** [comment]
It seems like there are known errors with [frontend-build](https://github.com/openedx/frontend-build) failing on Apple Silicon machines. Following up with someone on the issue.

**Comment by dianakhuang** [comment]
We believe we have resolved all the outstanding issues on Apple Silicon. If new ones crop up, we will resolve them separately.
