### ISSUE TITLE
Deprecate edx-platform `paver update_db`

### ISSUE THREAD

**Issue by robrap** [openedx-unsupported/devstack#1085]
`paver update_db` is an old way of running migrations for edxapp, but doesn't work in devstack and should just be removed. See https://github.com/openedx/edx-platform/issues/32252 for more details.

A/C:

- [ ] DEPR update_db
- [x] `make migrate` runs migrations in the current environment
- [ ] Remove references to using update_db everywhere (doc, github workflow?)

Notes:

- Any existing devstack calls (e.g. in docs) should be changed to `make dev.migrate.lms+studio`
- The reference in devstack is commented out as of this commit: https://github.com/openedx/devstack/commit/4e8360448075864fa8da4aa9b39325b6150b0350 (may want to see why before deleting it?)
- 2U: See private https://twou.slack.com/archives/C04A66RDPEZ/p1686068124202099?thread_ts=1686067860.936839&cid=C04A66RDPEZ for recent incident of this issue.
- The ticket https://github.com/openedx/edx-platform/issues/32252 can be closed once this is completed.

**Comment by dianakhuang** [comment]
DEPR ticket created: https://github.com/openedx/edx-platform/issues/32683
