### ISSUE TITLE
Use invoke for task management and command execution

### ISSUE THREAD

**Issue by rlucioni** [openedx-unsupported/devstack#11]
[Invoke](https://github.com/pyinvoke/invoke) is a Python (2.6+ and 3.3+) task execution tool which takes inspiration from GNU Make and Ruby's Rake. It places an emphasis on minimal boilerplate and provides traditional flag-based style command-line parsing and automatic help-text generation; see the link for more.

We should use invoke instead of Make to avoid the need for arcane lines like [this](https://github.com/edx/devstack/blob/master/Makefile#L5) and unhelpful stuff like updating [this](https://github.com/edx/devstack/blob/master/Makefile#L1).

**Comment by macdiesel** [comment]
I think we would like to move to some type of shell system to invoke commands for a project like this. 

Cool I'll take a look at it, but this is ultimately out of scope for the devstack project.
