### ISSUE TITLE
Not compatible with latest version of docker-sync

### ISSUE THREAD

**Issue by amangano-edx** [openedx-unsupported/devstack#110]
The `dest` field has been removed as of docker-sync version 0.3+ (https://github.com/EugenMayer/docker-sync/wiki/1.2-Upgrade-Guide#dest-has-been-removed). This breaks our ability to run `make dev.sync.provision`.

**Comment by clintonb** [comment]
@amangano-edx would you submit a PR with a fix, please?

**Comment by amangano-edx** [comment]
@clintonb I'm not sure when I'll have the time. I'm not particularly familiar with docker or docker-sync, I just know that docker-sync doesn't currently work as described in our README.

**Comment by amangano-edx** [comment]
For now, the traditional docker build works fine.

**Comment by clintonb** [comment]
It would be ideal for others to get familiar with the technologies. In this case the fix should be pretty straightforward. You already did the hard part of linking to the instructions.

**Comment by amangano-edx** [comment]
@clintonb I agree that it would be great to have a better understanding of these technologies. I just don't have the time to dedicate to it right now.
