### ISSUE TITLE
Devstack volumes are not reliably destroyed

### ISSUE THREAD

**Issue by timmc-edx** [openedx-unsupported/devstack#1113]
`make dev.destroy` does not seem to always destroy all of the Docker volumes. After running it, I have sometimes seen the output of `docker volume ls` include some volume names starting with `devstack_`. This might account for some oddities around mysql80.

Haven't been able to reproduce this again, though.

(Ticket previously incorrectly stated that there was _no_ way command that deleted the volumes, but this was incorrect.)

**Comment by timmc-edx** [comment]
You know what? I was wrong, it totally does do this. destroy.sh runs `docker-compose down -v` and that -v refers to volumes. Maybe I ran the wrong command!

But... interestingly, `make dev.destroy` doesn't remove _all_ of the `devstack_*` volumes. Or, not always?

**Comment by rgraber** [comment]
Possible cause: `down -v` may only remove volumes for running containers and leave the others in place.

**Comment by rgraber** [comment]
Blocked pending more investigation by @timmc-edx

**Comment by timmc-edx** [comment]
Hmm, I tried running `make dev.destroy` while only mysql80 was running, but it correctly removed all of the other `devstack_*` volumes as well.

**Comment by timmc-edx** [comment]
We should document "look at `docker volume ls`" as a last-ditch troubleshooting step and then close this.

**Comment by timmc-edx** [comment]
PR to update the docs with this possibility: https://github.com/openedx/devstack/pull/1141
