### ISSUE TITLE
Needless call to seed_permissions_roles management command when provisioning demo course

### ISSUE THREAD

**Issue by timmc-edx** [openedx-unsupported/devstack#1129]
Devstack and the configuration repo both have scripts to provision a demo course. They first call the `import` management command (in cms contentstore), and then `seed_permissions_roles` (in lms discussions). However, the `import` command already performs the seeding:

https://github.com/openedx/edx-platform/blob/77cef4cd074ca03d2b73261674923eb96ac804bd/cms/djangoapps/contentstore/management/commands/import.py#L78

We can remove this extra management command call from several places:

- [provision-lms.sh in devstack](https://github.com/openedx/devstack/blob/1c242f9152dbd5f7219bf7152ad6cd1db74fd433/provision-lms.sh#L57)
  - https://github.com/openedx/devstack/pull/1142
- [util/jenkins/demo-course-provisioner.sh in configuration](https://github.com/openedx/configuration/blob/921bd4c9da42fce79b6eb8b0aca598f9c00da4a8/util/jenkins/demo-course-provisioner.sh#L37)
  - This appears to ultimately be used from [CreateSandbox.groovy in jenkins-job-dsl](https://github.com/edx/jenkins-job-dsl/blob/c9a258bc058b38552cdf1342d429f19a0c5fb65c/devops/jobs/CreateSandbox.groovy#L333) via `ansible-provision.sh`
- [playbooks/roles/demo/tasks/deploy.yml in configuration](https://github.com/openedx/configuration/blob/921bd4c9da42fce79b6eb8b0aca598f9c00da4a8/playbooks/roles/demo/tasks/deploy.yml#L51)
  - Confusingly, this role is also used by `ansible-provision.sh`, even though it appears to be an alternative way of provisioning demo courses.

Archaeological notes:

- The instance in devstack appears to have been a more recent one, [copied from elsewhere](https://github.com/openedx/devstack/commit/4e8360448075864fa8da4aa9b39325b6150b0350#diff-bae6483862e829a0e8ccf1a5ccdec25045ce6d0af619d1234a2149c4da22aaddR60) in late 2022. The oldest change I can find that adds the call is from 2013, [in the configuration repo](https://github.com/openedx/configuration/pull/486/files).
- But then in 2014, the import command was [changed to seed anyhow](https://github.com/openedx/edx-platform/pull/2196), which is a more complete fix. I think this means we can drop the explicit call to the seed management command.

**Comment by robrap** [comment]
We can ask TNL to review the PR.

**Comment by timmc-edx** [comment]
For remaining occurrences in configuration repo, maybe make a ticket to try deleting the surrounding code entirely, since we're probably not using that at all. (Roles, Jenkins stuff.)

**Comment by timmc-edx** [comment]
It looks like the other occurrences may still be in use. Removing both: https://github.com/openedx/configuration/pull/6974
