### ISSUE TITLE
[Bug]: devpi runs at 100% CPU and is unavailable for quite some time after container started

### ISSUE THREAD

**Issue by timmc-edx** [openedx-unsupported/devstack#1131]
### Describe the bug that you are seeing.

After running `make lms-up` or similar, the devpi container burns CPU for about 20 minutes. (I think packages also cannot be installed in the LMS container during this, but something else may have been going on.)

According to https://github.com/devpi/devpi/issues/737 this may be the result of devpi fetching and processing indexes. The suggested `curl -H "Accept: application/json" http://localhost:3141/+status` shows that the `devpi_web_whoosh_index_queue_size` metric is above zero (and slowly falling), which appears to confirm this theory.

As far as I am aware, no one uses the devpi UI, which I _think_ is all the indexes are used for. So I think we may want to add `--indexer-backend null` to our docker image.

Not sure why this would have started recently, but I don't recall this happening until a month ago or so.

### Did this happen on the host (your machine or the remote instance) or in the container?

container

### What system was this issue seen on?

Linux

**Comment by timmc-edx** [comment]
I've tested this locally by modifying the devpi image to include `--indexer-backend null` [in the entrypoint script](https://github.com/openedx/configuration/blob/420bebddb2c887b13937b5a41f8004f9f5295bba/docker/build/devpi/docker-entrypoint.sh#L30) and it seemed to work fine.

**Comment by timmc-edx** [comment]
Moving to blocked for now; we may end up getting rid of devpi entirely: https://github.com/openedx/devstack/issues/1137

**Comment by rgraber** [comment]
Closing in favor of https://github.com/openedx/devstack/issues/1137
