### ISSUE TITLE
Document undocumented features of devstack (e.g. with-watchers)

### ISSUE THREAD

**Issue by robrap** [openedx-unsupported/devstack#1134]
It was noted that `make dev.up.with-watchers` was not documented. 

- Are there other features in the Makefile that are not documented and should be? 
- Should we just be telling people to review the whole Makefile to learn about potential features? (Not recommended)

**Comment by jmbowman** [comment]
The command is briefly documented in `make help`.  Maybe we just want to dump that output into a doc page so it's searchable?

**Comment by robrap** [comment]
Completed: https://github.com/openedx/devstack/pull/1180
