### ISSUE TITLE
Document pkg-config and devstack update help

### ISSUE THREAD

**Issue by robrap** [openedx-unsupported/devstack#1136]
A/C

- [x] Add a section in the troubleshooting doc for how to update devstack and noting that it's a good catch-all 
- [x] Add a "resolved issues" section of issues that should be resolved by updating. Include the pkg-config error here. Clarify that the solution here is to update.

Proposal:
* Add a section for "Devstack reboot" to troubleshooting doc has, which is about just getting the latest devstack changes and latest images and restarting to see if someone else has already resolved some issue. This might be a third top-level item. Explain that this is a general step, when all else fails, but you don't yet want to start from scratch and lose all your data.
* Add a section for the `pkg-config` issue that just points someone doing a devstack reboot. Include the following exception information: 
![Image](https://user-images.githubusercontent.com/14576445/256657305-55d25395-87cc-4543-a492-bf94b8b4b0d0.png)

Related notes:
- stop/up keeps shell history.
- stop/pull/up wipes shell history.
- Do we want to clarify this in this doc or in any other docs for devstack usage?

**Comment by timmc-edx** [comment]
Is the bulk of this still needed now that https://github.com/edx/edx-arch-experiments/issues/349 has largely merged? Can this be turned into a ticket just for how to pull new images effectively?

**Comment by robrap** [comment]
I believe this ticket is still needed.
1. A tip for how to update devstack properly seems like it would be useful for many cases as a last ditch effort to fix issues.
2. Regarding pkg-config, I think it would be useful to have issues documented that will become obsolete once everyone is up-to-date, but will help people that aren't there yet. Maybe the doc described in https://github.com/openedx/devstack/issues/1144 is a better place for these types of issues?

**Comment by rgraber** [comment]
https://github.com/openedx/devstack/pull/1161
