### ISSUE TITLE
Remove devpi from devstack

### ISSUE THREAD

**Issue by timmc-edx** [openedx-unsupported/devstack#1137]
While working on https://github.com/openedx/devstack/issues/1131 I discovered that devpi didn't seem to be used by lms and cms.

- From [a search for the port number on GitHub](https://github.com/search?type=code&q=(org%3Aopenedx+OR+org%3Aedx)+%2F\b3141\b%2F), it looks like the only reference is in the configuration repo's `devpi_consumer` role, which creates `/dev/.pip/pip.conf`. (This is also mentioned in devstack's own documentation on devpi.)
- The lms and cms images do not contain a `/dev/.pip/pip.conf` (presumably this role is not used when building the images any more) and the devpi logs do not show any traffic.
- If I create the config file on lms, then the devpi logs start showing traffic

The image was originally added as a caching layer for devstack users with slow network connections, but due to inefficiencies in the Ansible-based image build it ends up at 1.69 GB, mitigating most or all of the package caching benefits.  And the cache is really only useful when running `make upgrade` in multiple services with similar dependencies or repeatedly running `make upgrade` on the same old base service image.

Given that the devpi image itself is causing size and CPU issues and the benefits are seemingly small and hard to quantify, let's remove this from devstack.

**Comment by iamsobanjaved** [comment]
Related PRs:
- https://github.com/openedx/devstack/pull/1150
- https://github.com/openedx/configuration/pull/6981
