### ISSUE TITLE
Remove legacy elasticsearch images

### ISSUE THREAD

**Issue by jmbowman** [openedx-unsupported/devstack#1155]
A/C

- [ ] Devstack no longer references elasticsearch or elasticsearch7 images
- [ ] If there is a reason we keep them around, remove the dependency

`docker-compose.yml` still includes `elasticsearch` and `elasticsearch7` images even though all the services have already switched to using the `elasticsearch710` image.  Remove these older images from the file unless you find some obscure reason we need to keep them around.

**Comment by rgraber** [comment]
https://github.com/openedx/devstack/pull/1163
