### ISSUE TITLE
Install watchman via Ubuntu packages

### ISSUE THREAD

**Issue by jmbowman** [openedx-unsupported/devstack#1220]
We originally added watchman to our devstack images (to reduce Django runserver CPU utilization) back in February 2020: https://openedx.atlassian.net/browse/BOM-1241.  We installed it from GitHub releases because it wasn't in the current Ubuntu LTS, but it was added to Ubuntu 20.04 2 months later.  Many of the Dockerfiles (and the configuration repo) now install pretty stale versions of this package.  Switch over to installing the Ubuntu package instead, which should both keep us up to date with security patches and simplify the Dockerfiles.

Considered but rejected: periodically updating the GitHub release we install.  It looks like it's auto-released weekly and there's no changelog, so that feels like a high risk of breakage for something we don't really need the latest features from.

**Comment by irtazaakram** [comment]
Hi @jmbowman,

Watchman official docs https://github.com/facebook/watchman/blob/96b845a027fc4f4aeaa271abe3c688c429c0259c/website/_docs/install.markdown#ubuntu-prebuilt-debs suggest to not install watchman via ubuntu packages as it is dated.

> Warning: Do not install the Ubuntu-supplied Watchman package. It is old and missing security, bug, and performance fixes.

Thanks,

**Comment by jmbowman** [comment]
Sorry for the delay in replying.  Summarizing from the meeting today: we can go with a newer release from GitHub for now, but should reconsider when Ubuntu 24.04 comes out and/or set up a method of automating upgrades of this across repos.
