### ISSUE TITLE
[Bug]: Docker complains about the projet name

### ISSUE THREAD

**Issue by anaslaham** [openedx-unsupported/devstack#1248]
### Describe the bug that you are seeing.

when starting the development environment using `make dev.provision` docker compose shows the following error:
```bash
invalid project name "devstack-quince.master": must consist only of lowercase alphanumeric characters, hyphens, and underscores as well as start with a letter or number
```

Additional info:
`OS: Fedora Linux 39 (Workstation Edition) x86_64`
`Docker version 24.0.7, build afdd53b`
`Docker Compose version v2.21.0`
`OPENEDX_RELEASE=quince.master`

### Did this happen on the host (your machine or the remote instance) or in the container?

my machine running the dev env

### Steps to reproduce.

After running `make dev.clone.https`
Simply run `make dev.provision`

### What system was this issue seen on?

Linux

**Comment by rgraber** [comment]
Hi @anaslaham , thanks for your bug submission!
In general, we suggest using [Tutor](https://docs.tutor.edly.io/dev.html/) for developing off named releases. We will soon be deprecating that part of devstack.

That said, it's possible this could be a simple fix of just removing the period when we generate the project name [here](https://github.com/openedx/devstack/blob/a43aa5e06582ef4c8ec4e6e1f0c35334800d4bb2/options.mk#L35C2-L35C2). However, I'm not sure if anything in our BTR process assumes a specific project name. I have reached out to them to ask.

**Comment by rgraber** [comment]
This should be fixed with https://github.com/openedx/devstack/pull/1252. We will probably not pursue this work much further since very few people use devstack to develop off release branches.
