### ISSUE TITLE
Document Docker-Sync Troubleshooting Steps

### ISSUE THREAD

**Issue by clintonb** [openedx-unsupported/devstack#125]
1. Stop containers: `make stop`
2. Stop Docker-Sync: `docker-sync stop`
3. Clean sync volumes: `docker-sync clean`

This should probably be incorporated into a Make target, similar to `clean-marketing-sync`. Renaming it to `clean`, and moving it to `Makefile` should be sufficient.

Users should be using Docker Sync `0.4.6`, or above. 
* Check version: `docker-sync --version`
* Upgrade `gem update docker-sync`

**Comment by macdiesel** [comment]
Docs updated here, not making a make target for now as it's desired to move away from docker sync when we can.

https://github.com/edx/devstack/pull/192
