### ISSUE TITLE
Problem lauching first instance with custom requirements.

### ISSUE THREAD

**Issue by SalahAdDin** [openedx-unsupported/devstack#129]
I'm working with this dev stack.

I have made many launches before this problem and all time was well. I made changes in `requirements/base.txt` in `edx-platform` and after tested it i pull this changes to my custom branch in my fork.

I proceed to launch this fork in the server by first time and i got this error:
```bash
Creating edx.devstack.lms ... done
++ docker-compose exec lms bash -c 'source /edx/app/edxapp/edxapp_env && cd /edx/app/edxapp/edx-platform && NO_PYTHON_UNINSTALL=1 paver install_prereqs'
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
test `npm config get registry` = "https://registry.npmjs.org/" || (echo setting registry; npm config set registry https://registry.npmjs.org/)
make: *** [Makefile:23: dev.provision.run] Error 137
```

I proceed to test my custom fork in local and i got the same error:
```bash
Creating edx.devstack.lms ... done
++ docker-compose exec lms bash -c 'source /edx/app/edxapp/edxapp_env && cd /edx/app/edxapp/edx-platform && NO_PYTHON_UNINSTALL=1 paver install_prereqs'
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
test `npm config get registry` = "https://registry.npmjs.org/" || (echo setting registry; npm config set registry https://registry.npmjs.org/)
make: *** [Makefile:23: dev.provision.run] Error 137
```

So, i tested with the `master` branch, without my changes in these branch, but making some changes in the same file; i got these error:
```bash
++ docker-compose exec lms bash -c 'source /edx/app/edxapp/edxapp_env && cd /edx/app/edxapp/edx-platform && NO_PYTHON_UNINSTALL=1 paver install_prereqs'
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
Node prereqs unchanged, skipping...
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
NO_PYTHON_UNINSTALL is set. No attempts will be made to uninstall old Python libs.
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/pre.txt
make: *** [Makefile:23: dev.provision.run] Error 137
```

So, finally i proceed to remove all changes and launches again and:
```bash
++ docker-compose exec lms bash -c 'source /edx/app/edxapp/edxapp_env && cd /edx/app/edxapp/edx-platform && NO_PYTHON_UNINSTALL=1 paver install_prereqs'
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
Node prereqs unchanged, skipping...
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
NO_PYTHON_UNINSTALL is set. No attempts will be made to uninstall old Python libs.
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/pre.txt
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/github.txt
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/local.txt
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/base.txt
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/paver.txt
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/post.txt
pip freeze > /edx/app/edxapp/edx-platform/test_root/log/pip_freeze.log
++ docker-compose restart lms
```

Which is the commonly denominator in both problems? `PAVER`.

How can we launch in a first instance of our custom libraries with docker?

I can't understand it, i had to remove the repository, download again and modify it manually before to launch by first time.

The problem with this is that each time that we want make changes in the server we have to remove all source, clone again, and make all changes manually, as you can see this is not propperly and waste many time.

We can't do this all time that we made changes in requirements.

**Comment by clintonb** [comment]
Personally, I avoid Paver. It obfuscates too much. I would update the command to execute `pip`/`npm` directly—without Paver—before running the server.

**Comment by SalahAdDin** [comment]
@clintonb But, then, how can i modify the `provision` file for install all requirements?

**Comment by clintonb** [comment]
Why do you need to modify provision?

**Comment by SalahAdDin** [comment]
For example i want add some package for my environment, or i need add a new package for implements a new feature
Just know i saw thet `ecommerce` is broken because `npm` building failed, so, again i have to rebuild all project and again i will have problems.

**Comment by clintonb** [comment]
The change I described achieves that without having to modify the provision target.

**Comment by SalahAdDin** [comment]
I only modifyed `requirements/base.txt` in edx-platform.
Only this change broke all.

**Comment by clintonb** [comment]
I think you misunderstood my comment.

You need only modify `docker-compose.yml`.

Current:
```yaml
  lms:
    command: bash -c 'source /edx/app/edxapp/edxapp_env && python /edx/app/edxapp/edx-platform/manage.py lms runserver 0.0.0.0:18000 --settings devstack_docker'
```

Proposed:
```yaml
  lms:
    command: bash -c 'source /edx/app/edxapp/edxapp_env && npm install && pip install-r <path-to-file> &&  python /edx/app/edxapp/edx-platform/manage.py lms runserver 0.0.0.0:18000 --settings devstack_docker'
```

**Comment by SalahAdDin** [comment]
For example now i have these problem:
![rotoecommerce](https://cloud.githubusercontent.com/assets/5034215/26645339/5b41a788-4640-11e7-8f61-bc1af87292e7.png)

I have to re do `make dev.provision` and i will get the error because these file are modified.

**Comment by clintonb** [comment]
Is your issue with LMS or ecommerce? Your ecommerce screenshot is unrelated to this issue since we don't use Paver for that service, and provision works without issue.

**Comment by SalahAdDin** [comment]
But is you see `make dev.provision` you can find that it use `paver` for i don't know what things.

For this reason we can't launch the stack the first time from our custom fork, we have to begins from `edx` source and after it change to our fork or whatever.

**Comment by clintonb** [comment]
The use case you describe is not currently supported out of the box, and probably won't be anytime soon. I recommend building your own images. See the README for the link to edx/configuration.

**Comment by SalahAdDin** [comment]
Own image for what?

**Comment by clintonb** [comment]
Your own Docker image, with your requirements.

**Comment by SalahAdDin** [comment]
But i don't need a new docker image, i'm only modifying a single file in `edx-platform` folder: `requirements/base.txt`. 
I pull this change to my own fork.

In the server or whatever other place i clone this fork, i proceed to provide all environtments and i get this error all time.

**Comment by clintonb** [comment]
Okay. These details were missing from your initial post. Make sure you are slotting enough resources to Docker. I recommend at least 8GB and 4CPUs. Look at the logs in Kitematic to debug failures.

**Comment by SalahAdDin** [comment]
I have many resources here: 16gb and 8cpus.

1. I made a modification in `requierements/base.txt` in my fork from `edx-platform`.
2. I clone this fork.
3. I launch `make dev.provision` from devstack.

Get those errors.

**Comment by SalahAdDin** [comment]
```bash
++ docker-compose exec lms bash -c 'source /edx/app/edxapp/edxapp_env && cd /edx/app/edxapp/edx-platform && NO_PYTHON_UNINSTALL=1 paver install_prereqs'
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_node_prereqs
test `npm config get registry` = "https://registry.npmjs.org/" || (echo setting registry; npm config set registry https://registry.npmjs.org/)
npm install
Makefile:23: recipe for target 'dev.provision.run' faileduri https://registry.npmjs.org/webpack
make: *** [dev.provision.run] Error 137
```

**Comment by SalahAdDin** [comment]
It seems that this sources doesn't made for server environments:
More than five time the system, a single AWS intance (Ubuntu 16.04, 16GB) is dumped, lagged or whatever word can i use, while try to install npm:
![ubuntu ip-172-31-20-76 devstack - terminal deepin_026](https://cloud.githubusercontent.com/assets/5034215/26690012/747ae9a6-4700-11e7-8775-c8df82f9296f.png)
![ubuntu ip-172-31-10-145 devstack - terminal deepin_025](https://cloud.githubusercontent.com/assets/5034215/26690014/771780e8-4700-11e7-942e-2fd54de62251.png)

All time paver is the problem!

**Comment by macdiesel** [comment]
@SalahAdDin I think these use cases are covered here https://github.com/edx/devstack/#how-do-i-upgrade-python-packages

As to your second problem a PR has landed to address webpack files not being built in LMS, I would suggest a similar approach to ecommerce. I have opened a ticket here to address this as we are turning off github issues in favor of JIRA.

https://openedx.atlassian.net/browse/PLAT-1661

**Comment by SalahAdDin** [comment]
I used console command with docker for install it with paver, i'm not sure about is a good solution, but for now is enough.
