### ISSUE TITLE
clone.sh: line 36: [: : integer expression expected

### ISSUE THREAD

**Issue by azizur** [openedx-unsupported/devstack#170]
I just got back to looking at Open edx again.

I am using docker `Version 17.06.0-ce-mac18 (18433)
Channel: stable
d9b66511e0`

When I run `make dev.clone` I am seeing this 
```
$ make dev.clone
./clone.sh
./clone.sh: line 36: [: : integer expression expected
```

**Comment by macdiesel** [comment]
@azizur What shell and version are you using?

**Comment by macdiesel** [comment]
Also is the variable $SHALLOW_CLONE set in your environment when you run this?

**Comment by azizur** [comment]
```
$ bash -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

```

**Comment by macdiesel** [comment]
This should be fixed with https://github.com/edx/devstack/pull/184.
