### ISSUE TITLE
Stop docker-compose after provisioning

### ISSUE THREAD

**Issue by clintonb** [openedx-unsupported/devstack#18]
The provisioning script currently brings the services online, but does not take them down after completion. Update the provisioning script to take the services down _if they were not already running_. If they were running, assume the user wants to keep them running.

**Comment by clintonb** [comment]
This is *extremely* minor relative to the other issues.

**Comment by doctoryes** [comment]
Minor it is - yet, I feel that `make provision` should mean: 
"Get everything ready for a `make up` to be run."
instead of a combination of `make provision` and `make up`.

**Comment by clintonb** [comment]
I just realized why this won't work: containers are ephemeral. We are still using containers as if they are static VMs. In an ideal world `make provision` simply runs migrations and any tasks necessary to create longterm data (e.g. demo course/users). Prerequisites and static assets are already in the images.

We aren't in this ideal world. Today, if your container gets deleted, so do any assets or prerequisites you installed. Until we get to a more streamlined build process, one solution is to store the prerequisites and assets in named volumes that can be reattached to the containers as they are created and deleted.

**Comment by macdiesel** [comment]
Going to close this, the assets issue has been resolved for LMS/CMS. Doing this for IDAs is covered in this ticket: https://openedx.atlassian.net/browse/PLAT-1661.

As to installing requirements, this is covered in the docs and is a known thing. Images build for each checkin, use the latest tag.
