### ISSUE TITLE
`make dev.provision` [demo: create some test users] task fails

### ISSUE THREAD

**Issue by gsong** [openedx-unsupported/devstack#186]
### What steps will reproduce the problem?

1. `make dev.provision`

### What is the expected output?

Successful provisioning.

### What operating system and Docker?

MacOS 10.12.5, Docker version 17.06.0-ce, build 02c1d87

### Please provide any additional information below

<details>
<summary>Ansible task log</summary>
<pre>
TASK [demo : create some test users] *******************************************
 [WARNING]: Exception in safe_eval() on expr: [{u'username': u'honor', u'is_superuser': False, u'hashed_password':
u'pbkdf2_sha256$20000$TjE34FJjc3vv$0B7GUmH8RwrOc/BvMoxjb5j8EgnWTt3sxorDANeF7Qw=', u'is_staff': False, u'email': u'honor@example.com'}, {u'username': u'audit', u'is_superuser': False,
u'hashed_password':
u'pbkdf2_sha256$20000$TjE34FJjc3vv$0B7GUmH8RwrOc/BvMoxjb5j8EgnWTt3sxorDANeF7Qw=', u'is_staff':
False, u'email': u'audit@example.com'}, {u'username': u'verified', u'is_superuser': False,     u'hashed_password':
u'pbkdf2_sha256$20000$TjE34FJjc3vv$0B7GUmH8RwrOc/BvMoxjb5j8EgnWTt3sxorDANeF7Qw=', u'is_staff': False, u'email': u'verified@example.com'}, {u'username': u'staff', u'is_superuser': False,
u'hashed_password':
u'pbkdf2_sha256$20000$TjE34FJjc3vv$0B7GUmH8RwrOc/BvMoxjb5j8EgnWTt3sxorDANeF7Qw=', u'is_staff':
True, u'email': u'staff@example.com'}, Undefined] (name 'Undefined' is not defined)            
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'hashed_password'\n\nThe error appears to have been in '/edx/app/edx_ansible/edx_ansible/playbooks/roles/demo/tasks/deploy.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: create some test users\n  ^ here\n"}
        to retry, use: --limit @/edx/app/edx_ansible/edx_ansible/playbooks/edx-east/demo.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=30   changed=8    unreachable=0    failed=1
</pre>
</details>

I'm not sure if this is an upstream issue in [edx/configuration](https://github.com/edx/configuration).

**Comment by clintonb** [comment]
I am experiencing this issue. I suspect https://github.com/edx/configuration/pull/3952 introduced the issue.

```
TASK [demo : create some test users] *******************************************
 [WARNING]: Exception in safe_eval() on expr: [{u'username': u'honor', u'is_superuser': False, u'hashed_password':
u'pbkdf2_sha256$20000$TjE34FJjc3vv$0B7GUmH8RwrOc/BvMoxjb5j8EgnWTt3sxorDANeF7Qw=', u'is_staff': False, u'email':
u'honor@example.com'}, {u'username': u'audit', u'is_superuser': False, u'hashed_password':
u'pbkdf2_sha256$20000$TjE34FJjc3vv$0B7GUmH8RwrOc/BvMoxjb5j8EgnWTt3sxorDANeF7Qw=', u'is_staff': False, u'email':
u'audit@example.com'}, {u'username': u'verified', u'is_superuser': False, u'hashed_password':
u'pbkdf2_sha256$20000$TjE34FJjc3vv$0B7GUmH8RwrOc/BvMoxjb5j8EgnWTt3sxorDANeF7Qw=', u'is_staff': False, u'email':
u'verified@example.com'}, {u'username': u'staff', u'is_superuser': False, u'hashed_password':
u'pbkdf2_sha256$20000$TjE34FJjc3vv$0B7GUmH8RwrOc/BvMoxjb5j8EgnWTt3sxorDANeF7Qw=', u'is_staff': True, u'email':
u'staff@example.com'}, Undefined] (name 'Undefined' is not defined)

fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'hashed_password'\n\nThe error appears to have been in '/edx/app/edx_ansible/edx_ansible/playbooks/roles/demo/tasks/deploy.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: create some test users\n  ^ here\n"}
	to retry, use: --limit @/edx/app/edx_ansible/edx_ansible/playbooks/edx-east/demo.retry


```

**Comment by jibsheet** [comment]
Yeah, the config branch in general assumed it would always get a valid value, we fixed it for sandboxed by merging the internal config branch.  For devstacks I bet it needs a change in configuration to not always expect that value

**Comment by shrlyhe** [comment]
sorry for the bug, making fixes now

**Comment by bdero** [comment]
Linking to fix PR: https://github.com/edx/configuration/pull/3993

**Comment by gsong** [comment]
This has been resolved.
