### ISSUE TITLE
Django Debug Toolbar result details unavailable on LMS

### ISSUE THREAD

**Issue by ormsbee** [openedx-unsupported/devstack#194]
Clicking on any report in DDT to get more details (like "SQL") gives a progress indicator with no additional data.

![ddt_hanging](https://user-images.githubusercontent.com/41625/28639327-d9f0dfbc-7215-11e7-9b91-8592dd64b02d.png)

I haven't checked other IDAs.

**Comment by macdiesel** [comment]
@ormsbee I'm working on shutting down this issue tracker in favor of Jira, I've refiled your ticket here:
https://openedx.atlassian.net/browse/PLAT-1666
