### ISSUE TITLE
Ecommerce partner needs to be setup after provision

### ISSUE THREAD

**Issue by mjfrey** [openedx-unsupported/devstack#31]
- note the internal docker hostname needs to be used
- python manage.py create_or_update_site --site-id=1 --site-domain=localhost:18130 --partner-code=edX --partner-name='Open edX' --lms-url-root=http://edx.devstack.edxapp:18000 --theme-scss-path=sass/themes/edx.scss --payment-processors=cybersource,paypal --client-id=ecommerce-key --client-secret=ecommerce-secret --from-email staff@example.com

**Comment by clintonb** [comment]
Note that the `create_or_update_site` command needs to be updated to account for the fact that the issuer includes the "/oauth2" path.
