### ISSUE TITLE
ecommerce requirements are not installed during provision

### ISSUE THREAD

**Issue by mjfrey** [openedx-unsupported/devstack#33]
requirements are not installed needed to run make static.
We should also run make static by default during provision.

**Comment by clintonb** [comment]
All requirements _are_ installed in the image. However, the npm/bower dependencies are installed in the code repo. This means, when you use a host volume, the container uses the files on your local machine.

The fix here will probably be to run `make production-requirements` during provisioning just before we run `make static`. Even simpler, update the call to `make production-requirements static`.

**Comment by macdiesel** [comment]
Strategies to work around this are now documented in the readme: https://github.com/edx/devstack#how-do-i-upgrade-python-packages
