### ISSUE TITLE
Live reload for sass files not working

### ISSUE THREAD

**Issue by roderickmorales** [openedx-unsupported/devstack#37]
nginx is causing problems because is not letting me update CSS on the fly.

Thanks!
Roderick

**Comment by clintonb** [comment]
TODO
* Set `COMPRESS_OFFLINE` to `False` in settings (https://github.com/edx/course-discovery/pull/596)
* Allow nginx user to write to staticfiles directory
* Push new image to Docker Hub

**Comment by clintonb** [comment]
@roderickmorales @bderusha this is now resolved. Make sure you update edx/course-discovery to latest from master. Also, pull the latest Docker images with `docker-compose pull`.
