### ISSUE TITLE
Document how to delete containers and start over.

### ISSUE THREAD

**Issue by mjfrey** [openedx-unsupported/devstack#41]
Would like to know how to delete everything and start fresh.

**Comment by clintonb** [comment]
@mjfrey `make devstack.reset` will cleanup all of the containers. If you also want to get rid of data volumes (e.g. Mongo, MySQL, and Elasticsearch data), upgrade to the latest version of Docker for Mac and run [`docker system prune`](https://docs.docker.com/engine/reference/commandline/system_prune/).
