### ISSUE TITLE
Cannot save uploaded files 

### ISSUE THREAD

**Issue by bderusha** [openedx-unsupported/devstack#48]
When I upload an image (through django admin or otherwise) I get the following error:
`PermissionError: [Errno 13] Permission denied: '/edx/var/discovery/media'`

**Comment by clintonb** [comment]
I have fixed this in configuration by ensuring we (a) create this directory and (b) allow write access by nginx. The discovery image has been pushed; I'll push the others later.

I'd also like to expose a data volume for media so this data is maintained across container refreshes. I am leaving this open until we expose the volume.

**Comment by bderusha** [comment]
Thanks @clintonb This is working as expected now.

**Comment by MatthewPiatetsky** [comment]
@clintonb I am still seeing this issue

**Comment by clintonb** [comment]
This is not a priority for me—too busy with other work. If it is an issue for you, please do some digging to determine which directories have incorrect permissions. If you can do this, I can quickly update the images.

**Comment by macdiesel** [comment]
https://openedx.atlassian.net/browse/PLAT-1670
