### ISSUE TITLE
MongoDB runs out of storage space

### ISSUE THREAD

**Issue by clintonb** [openedx-unsupported/devstack#49]
Running edxapp tests creates a new database with every run. This leads to `mongod` shutting down due to lack of storage space. I fixed this by deleting all of the test databases.

```javascript
db.getMongo().getDBNames().forEach(function(name) {
    if(name.match("^test")) { 
        db.getMongo().getDB( name ).dropDatabase();
    }
});
```

We should find a way to have the tests cleanup after themselves.

**Comment by clintonb** [comment]
@edx/testeng how do we get around this issue for Vagrant-based devstacks?

**Comment by jzoldak** [comment]
@clintonb I've not heard of the issue before. Could be nobody had noticed. Dunno.

**Comment by clintonb** [comment]
I suspect this may have been resolved by https://github.com/edx/devstack/issues/52.

**Comment by clintonb** [comment]
Correction: the database cleanup has *not* been resolved. Space issues have been mitigated.

**Comment by macdiesel** [comment]
https://openedx.atlassian.net/browse/PLAT-1667
