### ISSUE TITLE
Update to Mongo 3.0

### ISSUE THREAD

**Issue by clintonb** [openedx-unsupported/devstack#52]
edX uses Mongo 3.0 in production. Devstack should reflect this fact. Use the [existing configuration](https://github.com/edx/configuration/tree/master/playbooks/roles/mongo_3_0) to pull, and configure, the container correctly. Specifically, note that we use the [WiredTiger storage engine](https://docs.mongodb.com/manual/core/wiredtiger/).

**Comment by clintonb** [comment]
@edx/devops is there anything we should be aware of regarding Mongo configuration? Is there certain functionality/configuration that only makes sense in production, and should be avoided for development?

**Comment by feanil** [comment]
No, I don't think so. Ideally, we would run three in all situations so that stepdowns and such could be tested in local environments. There might be other reasons why that doesn't make sense, in which case the single mongo should bi a replica set with one member and require auth to login.

**Comment by jibsheet** [comment]
The only other thing is you likely want the small journal setting, otherwise it'll try to create a multiple GB journal file that it only uses like 4k of.

**Comment by clintonb** [comment]
I'm not certain what the performance gains are for devstack; but, we need to eek out every gain we can to make this devstack's speed comparable to Vagrant.
