### ISSUE TITLE
Add support for running acceptance tests

### ISSUE THREAD

**Issue by clintonb** [openedx-unsupported/devstack#53]
I am unable to run the E-Commerce Service's acceptance tests. There are issues with `geckodriver` not being on the `PATH` and Firefox not being installed.

**Comment by clintonb** [comment]
A remote container (https://hub.docker.com/r/selenium/standalone-firefox/) may be a solution here.

**Comment by macdiesel** [comment]
This should be easy to add now that the new containers were added for LSM/Studio Acceptance tests.

https://openedx.atlassian.net/browse/PLAT-1665
