### ISSUE TITLE
Cannot run edxapp Jasmine tests

### ISSUE THREAD

**Issue by rlucioni** [openedx-unsupported/devstack#54]
These tests open and run in a Firefox browser. When run within a container, they just hang waiting for the browser to open, which never happens.

**Comment by clintonb** [comment]
Related to #53.

**Comment by clintonb** [comment]
@jzoldak thoughts on if/how we can incorporate the work you presented a couple weeks ago?

**Comment by jzoldak** [comment]
@clintonb  Hm, I'd need to think of the best thing for the Jasmine tests. For bok-choy tests (may be more applicable to #53, this is what I had going so far)  - add a selenium standalone container.

Still haven't gotten a chance to fully document it yet. :/
However I think you might be able to get what you need, with some tips for how to work around some  bugs and what not [here](../../edx-e2e-tests/blob/zoldak/document-docker/README.rst#using-the-browser-from-a-docker-container).

**Comment by clintonb** [comment]
Simple solution (borrowed from https://dzone.com/articles/how-to-run-karma-tests-in-a-docker-container): install xvfb and Firefox in the images. I just tested this, and it works. This solution is not ideal given that we don't necessarily want either of these applications installed on production images.

It would be ideal if there were a way to instruct Karma to use a remote browser. In that case we could use an external container, such as https://hub.docker.com/r/selenium/standalone-firefox/.

**Comment by macdiesel** [comment]
https://openedx.atlassian.net/browse/PLAT-1671
