### ISSUE TITLE
Install Cython

### ISSUE THREAD

**Issue by clintonb** [openedx-unsupported/devstack#62]
When debugging with PyCharm, PyCharm complains about Cython missing:

`warning: Debugger speedups using cython not found. Run '"/edx/app/credentials/venvs/credentials/bin/python" "/opt/.pycharm_helpers/pydev/setup_cython.py" build_ext --inplace' to build.`

Install this in the images so we can take advantage of it.

**Comment by macdiesel** [comment]
new ticket: https://openedx.atlassian.net/browse/PLAT-1664
