### ISSUE TITLE
Document PyCharm Integration

### ISSUE THREAD

**Issue by clintonb** [openedx-unsupported/devstack#65]
Explain how PyCharm users can setup a remote interpreter with Docker Compose.

**Acceptance Criteria**
1. Users can setup a remote interpreter pointing to Docker Compose.
2. Users can successfully run all services.
3. Users can successfully debug all services.

**Useful Links**
* https://www.jetbrains.com/help/pycharm/2016.3/docker.html
* https://www.jetbrains.com/help/pycharm/2016.3/configuring-remote-interpreters-via-docker-compose.html
* https://www.jetbrains.com/pycharm/nextversion/ (necessary to access Docker on unix socket `unix:///var/run/docker.sock`)

**Comment by clintonb** [comment]
@robrap let me know if you are still able to take this on.

**Comment by macdiesel** [comment]
Lots of work has been done on this, Thank you all for your help.
