### ISSUE TITLE
Determine how requirements should be managed

### ISSUE THREAD

**Issue by clintonb** [openedx-unsupported/devstack#7]
The discussion on #6 uncovered the fact that we—edX—don't have a best-practice around pinning dependencies. Determine this best practice and which, if any, tools we should use to implement/enforce this practice.

A few potential tools:
* https://github.com/nvie/pip-tools
* https://github.com/pypa/pipfile

**Comment by clintonb** [comment]
@rlucioni I created this so we don't lose the conversation from earlier.

**Comment by macdiesel** [comment]
https://openedx.atlassian.net/browse/PLAT-1669
