### ISSUE TITLE
Document host system requirements

### ISSUE THREAD

**Issue by jmatsushita** [openedx-unsupported/devstack#77]
Maybe worth adding to the README.md or an INSTALL.md? 

Installing from scratch on a Debian machine the following system requirements need to be fulfilled:
 - docker-ce (following the [recently updated installation manual](https://docs.docker.com/engine/installation/linux/debian/)
 - make
 - python-pip

Running `pip install -r requirements.txt` in the devstack folder will install `docker-compose`.

**Comment by macdiesel** [comment]
done.
