### ISSUE TITLE
Install elasticsearch-head

### ISSUE THREAD

**Issue by clintonb** [openedx-unsupported/devstack#8]
The [elasticsearch-head plugin](https://mobz.github.io/elasticsearch-head/) provides a nice UI for viewing indices and running queries. Install it on the Elasticsearch service to aid development.

**Comment by rlucioni** [comment]
What about creating an Elasticsearch image with this installed instead of forcing people to run a separate command?

**Comment by clintonb** [comment]
Yep. I was thinking about that last night. That makes the most sense. The only question for me is should the Dockerfile live here or in configuration?

**Comment by rlucioni** [comment]
I'd just put it here for now and be done with it. If it needs to move later we can make that happen.

**Comment by rlucioni** [comment]
Since we're already mounting volumes, check out this option: https://github.com/dockerfile/elasticsearch/issues/4#issuecomment-48705656.
