### ISSUE TITLE
Watching assets and make devstack.start.watch?

### ISSUE THREAD

**Issue by jmatsushita** [openedx-unsupported/devstack#80]
Hi there,

I'm wondering whether watching assets is supported in the devstack? Here's what I think I've understood so far:
 - `paver watch_assets` just results in:

```
# paver watch_assets
---> pavelib.assets.watch_assets
find /edx/app/edxapp/edx-platform/lms /edx/app/edxapp/edx-platform/cms /edx/app/edxapp/edx-platform/common -type f -name "*.coffee"
Starting asset watcher...
```

But changing sass files doesn't do anything, presumably because by default its only watching coffee files.

 - `paver update_assets --watch --settings devstack_docker`

Triggers a recompile and collects the assets but doesn't keep the watch process. (maybe related to the [background mode](https://github.com/edx/edx-platform/blob/open-release/ficus.1rc4/pavelib/assets.py#L740)? although no process seems to be running after that).

 - `paver update_assets --watch --debug --settings devstack_docker`

Given that debug [deactivates the background mode](https://github.com/edx/edx-platform/blob/open-release/ficus.1rc4/pavelib/assets.py#L848) I tried this too, but although it does keep a watch process in the foreground and triggers recompiles on file changes correctly it doesn't collect the assets. 

It seems from #64 that other apps have other approaches to watching assets and recompiling.

It would be great if correct settings were wrapped up in `make devstack.start.watch` command!

Cheers,

Jun

**Comment by macdiesel** [comment]
We are shutting down this issue tracker, this issue has been moved here:
https://openedx.atlassian.net/browse/PLAT-1663
