### ISSUE TITLE
Make target improvements

### ISSUE THREAD

**Issue by rlucioni** [openedx-unsupported/devstack#83]
Some of the existing target names are hard to work with and/or redundant. I think we can do better.

To be more precise:
1. The `devstack.` prefix. What does this add? Can we get rid of it?
2. Targets that rename/mask/shadow perfectly good Docker or Docker Compose names. For example, using `start` and `reset` instead of `up` and `down`, or (less painful) `update-images` instead of `pull`. Can we stick to the names used by Docker and Docker Compose where possible? We have the help target to explain where necessary.
3. Targets for running shells. The names for these can be more explicit. For example, `make <play>-shell`. "Open" means different things to different people (e.g., open a browser).

There may be other improvements, but this seems like a good place to start.

@clintonb FYI.

**Comment by clintonb** [comment]
I like all of these proposals.

**Comment by rlucioni** [comment]
Great! PR incoming.

![](https://media.giphy.com/media/bKnEnd65zqxfq/giphy.gif)
