### ISSUE TITLE
401 for forum

### ISSUE THREAD

**Issue by Xpecya** [openedx-unsupported/devstack#873]
i cloned the code from devstack and finish the get started
but requests to forum is always 401 without content

W, [2021-12-22T08:17:57.346982 #195]  WARN -- : NewRelic agent library not installed
W, [2021-12-22T08:17:57.598858 #195]  WARN -- : Overwriting existing field _id in class User.
W, [2021-12-22T08:17:57.638707 #195]  WARN -- : MONGODB | Unsupported client option 'max_retries'. It will be ignored.
W, [2021-12-22T08:17:57.639088 #195]  WARN -- : MONGODB | Unsupported client option 'retry_interval'. It will be ignored.
W, [2021-12-22T08:17:57.639212 #195]  WARN -- : MONGODB | Unsupported client option 'timeout'. It will be ignored.
W, [2021-12-22T08:17:57.682932 #195]  WARN -- : NewRelic agent library not installed
[2021-12-22 08:17:57] INFO  WEBrick 1.4.2
[2021-12-22 08:17:57] INFO  ruby 2.5.7 (2019-10-01) [x86_64-linux]
== Sinatra (v1.4.8) has taken the stage on 4567 for development with backup from WEBrick
[2021-12-22 08:17:57] INFO  WEBrick::HTTPServer#start: pid=195 port=4567
192.168.3.233 - - [22/Dec/2021:08:20:28 +0000] "GET / HTTP/1.1" 401 - 0.0018
192.168.3.233 - - [22/Dec/2021:08:20:28 UTC] "GET / HTTP/1.1" 401 0
- -> /
192.168.3.233 - - [22/Dec/2021:08:22:17 +0000] "GET / HTTP/1.1" 401 - 0.0004
192.168.3.233 - - [22/Dec/2021:08:22:17 UTC] "GET / HTTP/1.1" 401 0
- -> /
192.168.3.233 - - [22/Dec/2021:08:22:28 +0000] "GET /api HTTP/1.1" 401 - 0.0003
192.168.3.233 - - [22/Dec/2021:08:22:28 UTC] "GET /api HTTP/1.1" 401 0
- -> /api
192.168.3.233 - - [22/Dec/2021:08:22:50 +0000] "GET /api/v1 HTTP/1.1" 401 - 0.0003
192.168.3.233 - - [22/Dec/2021:08:22:50 UTC] "GET /api/v1 HTTP/1.1" 401 0
- -> /api/v1
192.168.3.233 - - [22/Dec/2021:08:22:53 +0000] "GET /api/v2 HTTP/1.1" 401 - 0.0004
192.168.3.233 - - [22/Dec/2021:08:22:53 UTC] "GET /api/v2 HTTP/1.1" 401 0
- -> /api/v2
192.168.3.233 - - [22/Dec/2021:08:23:10 +0000] "GET /swagger-ui HTTP/1.1" 401 - 0.0003
192.168.3.233 - - [22/Dec/2021:08:23:10 UTC] "GET /swagger-ui HTTP/1.1" 401 0
- -> /swagger-ui
192.168.3.233 - - [22/Dec/2021:08:33:38 +0000] "GET /api/v1 HTTP/1.1" 401 - 0.0003
192.168.3.233 - - [22/Dec/2021:08:33:38 UTC] "GET /api/v1 HTTP/1.1" 401 0
- -> /api/v1

here's the log. waiting for help

**Comment by kdmccormick** [comment]
Hey @Xpecya, if you're looking for help, your best bets are the Open edX forums (discuss.openedx.org) or the Open edX Slack instance. We're using GitHub issues in this repository mostly for issue tracking.
