### ISSUE TITLE
error

### ISSUE THREAD

**Issue by quantrpeter** [openedx-unsupported/devstack#875]
~/workspace/devstack>make dev.clone
./repo.sh clone_ssh
Cloning into 'course-discovery'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
make[1]: *** [impl-dev.clone.ssh] Error 128
Would you like to assist devstack development by sending anonymous usage metrics to edX? Run `make metrics-opt-in` to learn more!
make: *** [dev.clone.ssh] Error 2

**Comment by kdmccormick** [comment]
@quantrpeter You need to either:
* [set up an SSH key with GitHub](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent), or
* use the non-SSH clone strategy (`make dev.clone.https`).

In the future, please use our [Slack](https://open.edx.org/blog/open-edx-slack/) or [forum](https://discuss.openedx.org/) to ask for help before opening an issue here.
