### ISSUE TITLE
Replace all occurances of 'studio' with 'cms'

### ISSUE THREAD

**Issue by kdmccormick** [openedx-unsupported/devstack#877]
## Context

Since [edx-platform ADR-13](https://github.com/openedx/edx-platform/blob/master/docs/decisions/0013-cms-vs-studio.rst#terminology-cms-vs-studio) was added, it's agreed the "cms" is the correct name of the webservice, whereas "studio" should only be used in a product context.

However, Devstack currently calls the service "studio". For example, to start CMS, Devstack users must run: `make dev.up.studio`; to attach to CMS, Devstack users can run: `make studio-attach`.

It may reduce confusion for Devstack users if the "studio" service (which is defined in docker-compose.yml, and referenced in docker-compose.*.yml, the Makefile, and other locations) were renamed to "cms". That would mean that users would run instead `make dev.up.cms`, `make cms-attach`, etc.

## Acceptance criteria

(this is my best guess; there may be missing steps)

* In docker-compose.yml, rename the "studio" service to "cms".
* Search the entire devstack repository for "studio". Wherever "studio" is a reference to the docker-compose service, rename it to "cms".
* Update the docs. For example, references to `make studio-shell` should be changed to `make cms-shell`.
* Make a forum announcement about the change. In the announcement, recommend that users:
  * first stop their platform: `make down`
  * then, pull new devstack code: `git pull`
  * then, confirm that they can start CMS: `make dev.up.cms`

**Comment by iamsobanjaved** [comment]
Related PR:
- https://github.com/openedx/devstack/pull/957
