### ISSUE TITLE
Upgraded git version in container causes pip to fail

### ISSUE THREAD

**Issue by Kelketek** [openedx-unsupported/devstack#923]
A [recent security update to git](https://github.blog/2022-04-12-git-security-vulnerability-announced/) likely prevents provisioning in most common cases for *NIX systems. It does for me at the moment. The issue works as follows:

1. git refuses to run any commands if a user other than the current one owns a repo directory, since commands in the .git directory could contain arbitrary commands.
2. The devstack runs processes within containers as the root user.
3. The repos the devstack operates on top of use the same file ownership attributes as the host machine.
4. Since git sees the disparity, it refuses to list remotes when queried
5. Cloned repos like codejail, when analyzed by pip for install, are queried for their remotes.
6. pip does not receive the output it expects, and so throws `pip._internal.vcs.versioncontrol.RemoteNotFoundError`

This problem can be worked around by shelling into the LMS and studio and running:

```
find /edx/app/edxapp/venvs/edxapp/src/ -type d -exec git config --global --add safe.directory {} \;
```

This will silence the error for the affected repos.

**Comment by ShreehariVaasishta** [comment]
I was setting up OpenEdx for the first time in my local system and ran into this issue. Thanks for sharing this workaround.

**Comment by timmc-edx** [comment]
This should now be fixed: https://github.com/openedx/configuration/pull/6732

**Comment by ShreehariVaasishta** [comment]
@timmc-edx Yes, it seems to be fixed now.

**Comment by timmc-edx** [comment]
@Kelketek  Feel free to reopen or mention in Slack if this is still broken after pulling images.
