### ISSUE TITLE
Switch to Ansible-free Docker images

### ISSUE THREAD

**Issue by jmbowman** [openedx-unsupported/devstack#943]
In order to advance implementation of both [OEP-45: Configuring and Operating Open edX](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0045-arch-ops-and-config.html) and [deprecation of the configuration repository](https://github.com/openedx/public-engineering/issues/51), we would like to switch devstack from using primarily Docker images built with Ansible code from the configuration repository to images built from Dockerfiles in each service's repository.  We hope this will also help simplify Tutor by providing better base images to derive from, with fewer workarounds and duplicated code blocks required in Tutor.

Please create sub-tasks in separate issues as appropriate, in this repository and/or each service needing changes to its Dockerfile or image upload process.  Services should be switched one at a time so the work can be done and tested incrementally.  The process should look something like the following for each service:

* Ensure that the repo's Dockerfile can create a base image which is appropriate for small production installations
* Ensure that the repo's Dockerfile also defines an additional image derived from the base which adds dependencies and configuration changes needed for development environments
* Check with the Tutor developers during code review to see if any further changes to the Dockerfile would help simplify Tutor
* Automate uploads of both images when code changes are merged
* Switch devstack to use the new Ansible-free development image, and do some basic testing to ensure it works before merging

Once all of the services are switched over, the existing Jenkins-based automation for uploading Ansible-based development images can be retired.  This will involve deactivation and then deletion of Jenkins jobs, followed by removal of associated code in the configuration and other repositories.

Subtasks

- [x] https://github.com/edx/portal-designer/issues/185
- [x] https://github.com/openedx/devstack/issues/960
- [x] https://github.com/openedx/devstack/issues/961
- [x] https://github.com/openedx/devstack/issues/946
- [x] https://github.com/openedx/edx-analytics-data-api/issues/579
- [x] https://github.com/openedx/xqueue/issues/861
- [x] https://github.com/openedx/edx-notes-api/issues/303
- [x] https://github.com/openedx/edx-analytics-dashboard/issues/1328
- [x] https://github.com/openedx/devstack/issues/962

**Comment by kdmccormick** [comment]
@jmbowman I had started this work a few months ago, but abandoned it in order to focus on Tutor. You can see some of my progress and findings here: https://github.com/openedx/devstack/issues/869 . In particular, you might find useful this PR, in which I was going to introduce Devstack toggles for Ansible vs Ansible-free images: https://github.com/openedx/devstack/pull/866

**Comment by jmbowman** [comment]
There should also be sub-tasks for LMS, Studio, and the [IDA cookiecutter](https://github.com/openedx/edx-cookiecutters/blob/master/cookiecutter-django-ida/%7B%7Bcookiecutter.repo_name%7D%7D/Dockerfile) (to make sure new services start off with a reasonable Dockerfile template).
