### ISSUE TITLE
any advice

### ISSUE THREAD

**Issue by lolbus** [openedx-unsupported/devstack#983]
trying to setup an analytic pipeline to connect my LMS to my Insights services using this devstack.. any  suggestion how to go about? 

https://github.com/openedx/edx-analytics-pipeline
referred me here mentioned that theres a mini guide on how to stack up a docker based analyticstack here.. 

but i couldnt find the subsection titled 'getting started on analytics'

**Comment by lolbus** [comment]
Do i really have to use the open-release/hawthorn.master branch just to be able to run make pull.analytics_pipeline?

Reference: as per taught by
https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/open-release-hawthorn.master/installation/install_analytics.html

**Comment by arbrandes** [comment]
@lolbus, please use [the forum](https://discuss.openedx.org) or the [#devstack](https://openedx.slack.com/archives/CDAG4KN2Chttps://openedx.slack.com/archives/CDAG4KN2C) channel in Slack for support.  Thanks!
